package com.example.gpstest.firebase
class customevents {

    companion object{

        val splash_open="splash_launched_"
        val onboarding="onboarding_launched_"
        val language_launch="language_screen_launched_"
        val premmium_launched="premmium_screen_launched_"
        val comapss="comapss_launched_"
        val sevenwonders="sevenwonders_launched_"
        val satelite="satelite_launched_"
        val homeactivity_open="homeactivity_launched_"
        val search="search_launched_"
        val nearby="nearby_launched_"
        val myloc="myloc_launched_"
        val navigate="navigate_activity_launched_"
        val navigation_view="navigationview_launched_"
        val getstarted="splash_btn_clicked_"
       val route_btn_clicked="route_btn_clicked_"
        val near_by_btn_clicked="near_by_btn_clicked_"
        val my_loc_btn_clicked="my_loc_btn_clicked_"
        val searchVoice_btn_clicked="search_btn_clicked_"
        val compass_btn_clicked="compass_btn_clicked_"
        val sevenwonders_btn_clicked="sevenwonders_btn_clicked_"
        val setellite_btn_clicked="satelite_btn_clicked_"
        val streets_btn_clicked="streets_btn_clicked_"
        val premmium_clicked="premmium_clicked_"
        val onb_next_clicked="onb_next_clicked_"
        val Mainactivity_open="mainactivity_launched_"
        val navigation_btn_clicked="navigation_btn_clicked_"
        val navigationCancel_btn_clicked="navigationcancel_btn_clicked_"
        val drawer_open="drawer_open_"
        val drawer_close="drawer_close_"
        val review_clicked="review_clicked_"
        val reviewdialog_showed="review_dialog_showed_"
        val share_clicked="share_clicked_"
        val rate_clicked="rate_clicked_"
        val feedback_clicked="feedback_clicked_"
        val languagee_screen="language_clicked_"
        val AI_Bot_clicked="ai_bot_clicked_"
        val AI_Bot_launched="ai_bot_launched_"
        val AI_Bot_sendbtn="ai_bot_sendbtn_clicked_"
        val AI_Bot_upgrade="ai_bot_upgrade_"

        val splash_disappear="splash_disappear_"
        val onboarding_disappear="onboarding_disappear_"
        val language_disappear="language_disappear_"
        val premimum_disappear="premmium_disappear_"
        val start_disappear="start_disappear_"
        val sevenwonders_disappear="sevenwonders_disappear_"
        val mainactivity_disappear="mainactivity_disappear_"
        val navigation_disappear="navigation_disappear_"
        val satelite_disappear="satelite_disappear_"
        val nearby_disappear="nearby_disappear_"
        val myloc_disappear="myloc_disappear_"
        val search_disappear="search_disappear_"
        val compass_disappear="compass_disappear_"
        val navigate_disappear="navigate_disappear_"

        val first_time_user="first_time_user_"
        val second_time_user="second_time_user_"
        val backpress_from_boarding="backpress_from_boarding_"
        val letsgo_boarding_clicked="letsgo_clicked_"
        val lang_apply="lang_apply_"
        val inter_normalload_request_sent="inter_load_request_sent"
        val inter_langload_request_sent="inter_lanload_request_sent"
        val inter_load_success="inter_load_success"
        val inter_load_failed="inter_load_failed"
    }
}